import React, { useEffect, useState } from 'react';
import { View, Text, StyleSheet, FlatList, Pressable, Alert } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { LinearGradient } from 'expo-linear-gradient';
import { Feather } from '@expo/vector-icons';
import { PatientAssessmentRecord, getAssessmentHistory, clearAssessmentHistory } from '../services/HistoryService';
import { COLORS, TYPOGRAPHY, SPACING, RADIUS, SHADOW } from '../theme/tokens';
import LoadingState from '../components/ui/LoadingState';

interface PatientHistoryScreenProps {
  onBack: () => void;
}

export default function PatientHistoryScreen({ onBack }: PatientHistoryScreenProps) {
  const insets = useSafeAreaInsets();
  const [history, setHistory] = useState<PatientAssessmentRecord[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    loadHistory();
  }, []);

  const loadHistory = async () => {
    setIsLoading(true);
    try {
      const data = await getAssessmentHistory();
      setHistory(data);
    } catch (error) {
      console.error('Failed to load history:', error);
      Alert.alert('Error', 'Failed to load patient history.');
    } finally {
      setIsLoading(false);
    }
  };

  const handleClearHistory = () => {
    Alert.alert(
      'Clear History',
      'Are you sure you want to delete all past assessment results? This cannot be undone.',
      [
        { text: 'Cancel', style: 'cancel' },
        { 
          text: 'Clear All', 
          style: 'destructive',
          onPress: async () => {
            try {
              await clearAssessmentHistory();
              setHistory([]);
            } catch (err) {
              Alert.alert('Error', 'Failed to clear history.');
            }
          }
        }
      ]
    );
  };

  const handlePrint = async (record: PatientAssessmentRecord) => {
    const { Share } = await import('react-native');
    
    let message = `🏥 SymptaCare Assessment Result\n`;
    message += `Date: ${new Date(record.date).toLocaleString()}\n\n`;
    message += `URGENCY LEVEL: ${record.triage.toUpperCase()}\n`;
    message += `Advice: ${record.advice}\n\n`;
    message += `📝 SYMPTOMS REPORTED:\n`;
    record.symptoms.forEach(s => {
      message += `- ${s.replace(/_/g, ' ')}\n`;
    });
    
    message += `\n*This report was generated by SymptaCare for informational purposes. Please consult a doctor for official medical advice.*`;
    
    try {
      await Share.share({
        message,
        title: 'My SymptaCare Assessment Result'
      });
    } catch (error) {
      console.error('Error sharing result', error);
    }
  };

  const getRiskColor = (risk: string) => {
    switch (risk) {
      case 'Red': return '#EF4444';
      case 'Amber': return '#F59E0B';
      default: return '#10B981';
    }
  };

  const getRiskLabel = (risk: string) => {
    switch (risk) {
      case 'Red': return 'Emergency';
      case 'Amber': return 'See Doctor';
      default: return 'Home Care';
    }
  };

  const renderItem = ({ item }: { item: PatientAssessmentRecord }) => {
    const riskColor = getRiskColor(item.triage);
    
    return (
      <View style={styles.card}>
        <View style={styles.cardHeader}>
          <View>
            <Text style={styles.dateText}>{new Date(item.date).toLocaleDateString()}</Text>
            <Text style={styles.timeText}>{new Date(item.date).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</Text>
          </View>
          <View style={[styles.riskBadge, { backgroundColor: riskColor + '20' }]}>
            <View style={[styles.riskDot, { backgroundColor: riskColor }]} />
            <Text style={[styles.riskText, { color: riskColor }]}>{getRiskLabel(item.triage)}</Text>
          </View>
        </View>

        <View style={styles.symptomsContainer}>
          <Text style={styles.sectionTitle}>Symptoms Reported:</Text>
          <View style={styles.pillsRow}>
            {item.symptoms.slice(0, 4).map((sym, i) => (
              <View key={i} style={styles.pill}>
                <Text style={styles.pillText}>{sym.replace(/_/g, ' ')}</Text>
              </View>
            ))}
            {item.symptoms.length > 4 && (
              <View style={styles.pillMore}>
                <Text style={styles.pillText}>+{item.symptoms.length - 4} more</Text>
              </View>
            )}
          </View>
        </View>

        <View style={styles.adviceContainer}>
          <Text style={styles.adviceText} numberOfLines={2}>{item.advice}</Text>
        </View>

        <Pressable 
          style={styles.printBtn}
          onPress={() => handlePrint(item)}
        >
          <Feather name="share" size={14} color={COLORS.brandBlue} style={{ marginRight: 6 }} />
          <Text style={styles.printBtnText}>Share / Save Note</Text>
        </Pressable>
      </View>
    );
  };

  return (
    <View style={styles.root}>
      {/* ── HEADER ── */}
      <View style={[styles.header, { paddingTop: insets.top + SPACING.md }]}>
        <Pressable onPress={onBack} style={styles.backBtn}>
          <Feather name="arrow-left" size={24} color={COLORS.brandNavy} />
        </Pressable>
        <Text style={styles.headerTitle}>My Assessment History</Text>
        {history.length > 0 ? (
          <Pressable onPress={handleClearHistory} style={styles.clearBtn}>
            <Feather name="trash-2" size={20} color={COLORS.error} />
          </Pressable>
        ) : (
          <View style={{ width: 44 }} />
        )}
      </View>

      <LinearGradient colors={['#F8FAFC', '#F1F5F9']} style={{ flex: 1 }}>
        {isLoading ? (
          <LoadingState message="Loading your history..." />
        ) : history.length === 0 ? (
          <View style={styles.emptyContainer}>
            <Feather name="clock" size={48} color={COLORS.borderLight} style={{ marginBottom: SPACING.md }} />
            <Text style={styles.emptyTitle}>No History Found</Text>
            <Text style={styles.emptySub}>Your past assessment results will appear here.</Text>
          </View>
        ) : (
          <FlatList
            data={history}
            keyExtractor={item => item.id}
            renderItem={renderItem}
            contentContainerStyle={styles.listContent}
            showsVerticalScrollIndicator={false}
          />
        )}
      </LinearGradient>
    </View>
  );
}

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: COLORS.bgPrimary,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: SPACING.lg,
    paddingBottom: SPACING.md,
    backgroundColor: 'white',
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderLight,
  },
  backBtn: {
    width: 44,
    height: 44,
    borderRadius: RADIUS.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.bgSurface,
  },
  clearBtn: {
    width: 44,
    height: 44,
    borderRadius: RADIUS.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: COLORS.brandNavy,
  },
  listContent: {
    padding: SPACING.lg,
    paddingBottom: SPACING.xxxl,
  },
  card: {
    backgroundColor: 'white',
    borderRadius: RADIUS.xl,
    padding: SPACING.lg,
    marginBottom: SPACING.md,
    ...SHADOW.sm,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: SPACING.md,
  },
  dateText: {
    fontSize: TYPOGRAPHY.size.base,
    fontWeight: '700',
    color: COLORS.brandNavy,
  },
  timeText: {
    fontSize: TYPOGRAPHY.size.sm,
    color: COLORS.textSecondary,
    marginTop: 2,
  },
  riskBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: RADIUS.pill,
  },
  riskDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginRight: 6,
  },
  riskText: {
    fontSize: TYPOGRAPHY.size.xs,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  symptomsContainer: {
    marginBottom: SPACING.md,
  },
  sectionTitle: {
    fontSize: TYPOGRAPHY.size.xs,
    fontWeight: '700',
    color: COLORS.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: SPACING.sm,
  },
  pillsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  pill: {
    backgroundColor: COLORS.bgSurface2,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: RADIUS.sm,
  },
  pillMore: {
    backgroundColor: COLORS.borderLight,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: RADIUS.sm,
  },
  pillText: {
    fontSize: 12,
    color: COLORS.textSecondary,
    fontWeight: '600',
  },
  adviceContainer: {
    backgroundColor: '#F8FAFC',
    padding: SPACING.md,
    borderRadius: RADIUS.md,
    marginBottom: SPACING.md,
  },
  adviceText: {
    fontSize: TYPOGRAPHY.size.sm,
    color: COLORS.textPrimary,
    fontStyle: 'italic',
  },
  printBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: SPACING.sm,
    borderTopWidth: 1,
    borderTopColor: COLORS.borderLight,
    marginTop: SPACING.sm,
  },
  printBtnText: {
    fontSize: TYPOGRAPHY.size.sm,
    fontWeight: '700',
    color: COLORS.brandBlue,
  },
  emptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: SPACING.xl,
  },
  emptyTitle: {
    fontSize: TYPOGRAPHY.size.lg,
    fontWeight: '800',
    color: COLORS.textPrimary,
    marginBottom: SPACING.xs,
  },
  emptySub: {
    fontSize: TYPOGRAPHY.size.base,
    color: COLORS.textSecondary,
    textAlign: 'center',
  }
});
